import type { NextPage } from "next";
import Head from "next/head";
import Register from "../components/Register";

import {signIn, register} from "../auth/auth"
import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { collection, addDoc, getDocs } from "firebase/firestore";
import {getAuth} from "firebase/auth"

const firebaseConfig = {
  apiKey: "AIzaSyBlMEnkyHKOUNZncSmOjXB3v1BEb_HJTY4",
  authDomain: "codebreaker-505ec.firebaseapp.com",
  projectId: "codebreaker-505ec",
  storageBucket: "codebreaker-505ec.appspot.com",
  messagingSenderId: "739772167053",
  appId: "1:739772167053:web:177c6ffcb1cc76f95583c4",
  measurementId: "G-8LRW0DG85C",
};

// Write to Database Example
async function writeToFireBase(db: any) {
  try {
    const docRef = await addDoc(collection(db, "users"), {
      first: "Ada",
      last: "Lovelace",
      born: 1815,
    });

    console.log("Document written with ID: ", docRef.id);
  } catch (e) {
    console.error("Error adding document: ", e);
  }
}

const Home: NextPage = () => {
  const app = initializeApp(firebaseConfig);
  const db = getFirestore(app);

  //writeToFireBase(db);
  let auth = getAuth();

  return (
    <div>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link rel="preconnect" href="https://fonts.gstatic.com/" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800;900&display=swap"
          rel="stylesheet"
        />
        <title>Code Breaker's Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register />
    </div>
  );
};

export default Home;
